echo "******************************"
echo "     System information "
echo "******************************"
echo "Operating system : $(uname)"
echo "******************************"
echo "     eth0 Configuration "
echo "******************************"
ifconfig eth0 | grep "inet addr"
echo "******************************"
echo "          Hostname "
echo "******************************"
echo "      "$HOSTNAME
echo "***********************"
echo "*** Network routing ***"
echo "***********************"
netstat -nr
echo "**************************************"
echo "*** Interface traffic information ***"
echo "**************************************"
netstat -i